### ISSUE TITLE
Fix LFortran to build this

### ISSUE THREAD

**Issue by certik** [certik/matmul#3]
Currently it fails with:
```console
+ FC=lfortran
+ cmake -Bbuild -DMATMUL_BLAS=OpenBLAS
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is unknown
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: /Users/ondrej/bin/lfortran
-- Check for working Fortran compiler: /Users/ondrej/bin/lfortran - works
-- Checking whether /Users/ondrej/bin/lfortran supports Fortran 90
-- Checking whether /Users/ondrej/bin/lfortran supports Fortran 90 - no
-- Found OPENBLAS: /Users/ondrej/mambaforge/envs/fastgpt/include  
-- Found OMP: /Users/ondrej/mambaforge/envs/fastgpt/include  


Configuration results
---------------------
Fortran compiler: /Users/ondrej/bin/lfortran
Build type: Release
Fortran compiler flags: 
Installation prefix: /usr/local
MATMUL_BLAS: OpenBLAS
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ondrej/repos/matmul/build
+ cmake --build build
[ 16%] Building Fortran object CMakeFiles/matmullib.dir/linalg_c.f90.o
[ 33%] Building Fortran object CMakeFiles/matmullib.dir/m.f90.o
[ 50%] Building C object CMakeFiles/matmullib.dir/linalg_openblas.c.o
[ 66%] Linking Fortran static library libmatmullib.a
[ 66%] Built target matmullib
[ 83%] Building Fortran object CMakeFiles/matmul.dir/main.f90.o
ASR verify pass error: ASR verify: Var::m_v `bb` cannot point outside of its symbol table
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 1937
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/ondrej/repos/lfortran/lfortran/src/bin/lfortran.cpp", line 897
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/lfortran/fortran_evaluator.cpp", line 346
    compiler_options, run_fn, infile);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 7969
    pass_manager.apply_passes(al, &asr, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 277
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/ondrej/repos/lfortran/lfortran/src/libasr/pass/pass_manager.h", line 153
    + passes[i]);
LCompilersException: Verify failed in the pass: array_op
make[2]: *** [CMakeFiles/matmul.dir/main.f90.o] Error 1
make[1]: *** [CMakeFiles/matmul.dir/all] Error 2
make: *** [all] Error 2
```

TODO:

* [ ] Create a minimal reproducible example and report it to LFortran
* [ ] Fix it
* [ ] See what else fails

**Comment by certik** [comment]
One can use LFortran via:
```diff
--- a/build.sh
+++ b/build.sh
@@ -2,6 +2,6 @@
 
 set -ex
 
-FC=gfortran cmake -Bbuild -DMATMUL_BLAS=OpenBLAS
-cmake --build build --parallel
+FC=lfortran cmake -Bbuild -DMATMUL_BLAS=OpenBLAS
+cmake --build build
 OMP_NUM_THREADS=1 build/matmul
```
